name: preview

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - '.github/workflows/test.yml'
      - 'assets/**'
      - 'docs/**'
      - 'example/**'
      - 'site/**'
      - 'test/**'
      - '.npmignore'
      - '.prettierignore'
      - '.prettierrc'
      - '.renovaterc.json'
      - '*.md'
      - 'LICENSE'

jobs:
  release:
    name: Release preview build
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Use Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          cache: 'npm'
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release preview version
        run: npx pkg-pr-new@0.0.50 publish --template './example'
